### ISSUE TITLE
Scanner not working after selecting value from select-box or date picker

### ISSUE THREAD

**Issue by vijaypaliwal** [SocketMobile/scanapi-cordova#4]
Scanner not working after selecting value from select-box or date picker with IOS APP

**Comment by EricGlaenzer** [comment]
Hi @vijaypaliwal ,
Do you still have an issue with this?
Thanks!

**Comment by EricGlaenzer** [comment]
Closing this issue since there is no answer. This Cordova repo is deprecated, it is best to use this one instead: https://github.com/SocketMobile/capturebasic-cordova-ios
